# global_frame: base_frame
global_frame: map
robot_base_frame: base_frame
# rolling_window: false
rolling_window: true
# width: 2
width: 2
# height: 2
height: 2
origin_x: -1.0
origin_y: -1.0

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
