global_frame: map
rolling_window: false

# By setting track_unknown_space to false, the unknown-area is treated like free-space and the local planner works perfectly fine.
track_unknown_space: false
# track_unknown_space: true
# tolerance: 1.0

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
